# 1.Write a NumPy program to create an array with the values 1, 7, 13, 105    and determine the size of the memory occupied by the array.


In [17]:
import numpy as np

In [18]:
arr = np.array([1,7,13,105])
print(f"Size = {arr.size}")

Size = 4


# 2. Write a NumPy program to create an element-wise comparison (greater,    greater_equal, less and less_equal) of two given arrays.


In [19]:
def function1():
    arr_1=np.array([18,63])
    arr_2=np.array([98,12])
    print(f"Greater= {np.greater(arr_1,arr_2)}")
    print(f"Greater Equal= {np.greater_equal(arr_1,arr_2)}")
    print(f"Less= {np.less(arr_1,arr_2)}")
    print(f"Less Equal= {np.less_equal(arr_1,arr_2)}")

In [20]:
function1()

Greater= [False  True]
Greater Equal= [False  True]
Less= [ True False]
Less Equal= [ True False]


# 3.  Write a NumPy program to create an array of 10 zeros, 10 ones, 10    fives, 10 tens, 10 twentys and 10 fiftys.

In [21]:
def function2():
    arr1=np.zeros(10)
    print(arr1)
    arr2=np.ones(10)
    print(arr2)
    arr3=np.ones(10) * 5
    print(arr3)
    arr4=np.ones(10) * 10
    print(arr4)
    arr4=np.ones(10) * 20
    print(arr4)
    arr4=np.ones(10) * 50
    print(arr4)
    

In [22]:
function2()

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
[10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
[20. 20. 20. 20. 20. 20. 20. 20. 20. 20.]
[50. 50. 50. 50. 50. 50. 50. 50. 50. 50.]


# 4.Write a NumPy program to create an array of integers from 30 to 70.

In [23]:
arr=np.arange(30,71)
print(arr)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


# 5. Write a NumPy program to create an array of integers from 50 to 95.

In [24]:
arr=np.arange(50,96)
print(arr)

[50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95]


# 6. Write a NumPy program to create an array of all even integers from 20 to 80.

In [25]:
arr=np.arange(20,80,2)
print(arr)

[20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66
 68 70 72 74 76 78]


# 7. Write a NumPy program to create an array of all odd integers from 20 to 80.

In [26]:
arr=np.arange(21,80,2)
print(arr)

[21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57 59 61 63 65 67
 69 71 73 75 77 79]


# 8. Write a NumPy program to generate an array of 15 random numbers from 10    to 40.


In [27]:
arr=np.random.randint(10,40,15)
print(arr)

[22 26 26 37 22 28 38 10 23 29 29 18 37 16 23]


# 9. Write a NumPy program to generate an array of 10 random numbers from 30    to 50.

In [28]:
arr=np.random.randint(30,50,10)
print(arr)

[42 39 46 36 32 33 33 42 48 45]


# 10. Write a NumPy program to generate an array of 20 random numbers from 50    to 90.


In [29]:
arr=np.random.randint(50,90,20)
print(arr)

[50 58 58 56 70 76 70 51 74 69 85 84 59 67 80 77 53 71 58 75]


# 11. Create any two arrays & perform various mathematical operations. i.e. Addition, Substraction, Multiplication, Divide.

In [30]:
arr1=np.array([6,13])
arr2=np.array([3,4])
print(f"Addition = {np.add(arr1,arr2)}")
print(f"Substraction = {(arr1-arr2)}")
print(f"Multiplication = {(arr1*arr2)}")
print(f"Divide = {(arr1/arr2)}")

Addition = [ 9 17]
Substraction = [3 9]
Multiplication = [18 52]
Divide = [2.   3.25]


# 12. Write a NumPy program to create a 3x4 matrix filled with values from 10     to 21.


In [38]:
arr=np.arange(10,22)
arr=arr.reshape((3,4))
print(arr)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


# 13. Write a NumPy program to create a 3x3 identity matrix, i.e. the diagonal     elements are 1, the rest are 0.

# 14. Write a NumPy program to find the number of rows and columns in a given     matrix. 


In [39]:
arr=np.arange(10,22)
arr=arr.reshape((3,4))
print(arr)
print(arr.shape)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
(3, 4)


# 15. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.

# 16. Write a NumPy program to create a 3x3x3 array filled with arbitrary values.

In [42]:
arr=np.random.random((3,3,3))
print(f"3x3x3 Array: {arr}")

3x3x3 Array: [[[0.02464766 0.93057664 0.14697164]
  [0.92131643 0.35825644 0.37872564]
  [0.19896509 0.43545163 0.01272006]]

 [[0.79289021 0.36872916 0.97051456]
  [0.04308535 0.94862392 0.92145549]
  [0.391957   0.46791493 0.58081158]]

 [[0.89757166 0.48615667 0.09834991]
  [0.54463511 0.54748547 0.31402118]
  [0.34124373 0.48769232 0.94163609]]]


# 17. Write a NumPy program to create a 2x3x4 array filled with arbitrary values.

In [44]:
arr=np.random.random((2,3,4))
print(f"2x3x4 Array: {arr}")

2x3x4 Array: [[[0.03260395 0.00308946 0.20001323 0.52306965]
  [0.99179922 0.54876479 0.91983442 0.03825608]
  [0.32564586 0.41489782 0.45604378 0.00204663]]

 [[0.26067113 0.71740073 0.79410963 0.11495892]
  [0.79598765 0.76142253 0.80501028 0.73291997]
  [0.89935305 0.27770109 0.00253532 0.73638007]]]


# 18. Write a NumPy program to convert a list of numeric values into a one-dimensional NumPy array.


In [45]:
list1=[12,24,36,48,60]
arr=np.array(list1)
print(f"One-D Array: {arr}")

One-D Array: [12 24 36 48 60]


# 19. Write a NumPy program to create a 3x3 matrix with values ranging from 2  to 10.

In [49]:
arr=np.arange(2,11)
arr=arr.reshape(3,3)
print(arr)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


# 20. Write a NumPy program to create an array with values ranging from 12 to 38.

In [32]:
arr=np.arange(12,38)
print(arr)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


# 21. Write a NumPy program to reverse an array (the first element becomes the last).

In [33]:
arr=np.array([11,22,33,44,55])
print(f"Reverse= {(arr[::-1])}")

Reverse= [55 44 33 22 11]


# 22. Write a NumPy program to convert an data type into to a floating type.

In [50]:
a = [1, 2, 3, 4, 5]
f = np.asfarray(a)
print(f"Data type into to a  floating type :{f}")

Data type into to a  floating type :[1. 2. 3. 4. 5.]


# 23. Write a NumPy program to convert a list array.

In [34]:
a = [1, 2, 3, 4, 5]
x = np.array(a)
print(x)

[1 2 3 4 5]


# 24. Write a NumPy program to get the element-wise remainder of an array of division.

In [35]:
arr1=np.array([656,72,890,96])
arr2=np.array([11,2,15,16])
print(f"Remainder= {arr1%arr2}")


Remainder= [7 0 5 0]


# 25.Write a NumPy program to get the element-wise remainder of an array of numbers from 20 to 50 which are divisible by 3.

In [36]:
arr1=np.arange(20,50)
print(f"Remainder= {arr1%3}")

Remainder= [2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1]
